### PR TITLE
allowing user to pass in loadTemplate and and renderTemplate

### PR DESCRIPTION
**Pull request by kyle-dorman**
functions. This will allow ubar to use other templating systems besides
handlebars if the user so chooses. If no template system is passed in,
ubar defualts to its tempalting system using handlebars

### CODE REVIEW

**Comment by kyle-dorman** [comment]
fixes issue #12

**Comment by GregM** [comment]
+1

**Comment by sanchezjjose** [comment]
+1

**Comment by archanks** [comment]
nice !

**Pull request closed without merging**
